<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OverTCP.Messaging\OverTCP.Messaging.csproj" />
    <ProjectReference Include="..\OverTCP\OverTCP.csproj" />
  </ItemGroup>

</Project>
